### ISSUE TITLE
Error getting `tokenizer_config.json` from `sd-turbo`

### ISSUE THREAD

**Issue by Titan-Node** [livepeer/ai-worker#27] opened 2024-02-11 19:24 UTC
**System: Windows 11**
Using the first huggingface command to get sd-turbo models 
```
huggingface-cli download stabilityai/sd-turbo --include "*.fp16.safetensors" "*.json" "*.txt" --exclude ".onnx" ".onnx_data" --cache-dir models
```
Got the following OS Error. It downloaded the `tokenizer_config.json` file but is 0kb and cannot open it on my system, which is really odd.
```
AppData\Local\Programs\Python\Python311\Lib\site-packages\huggingface_hub\file_download.py", line 916, in _create_symlink
    os.symlink(src_rel_or_abs, abs_dst)

OSError: [WinError 1314] A required privilege is not held by the client: '..\\..\\..\\blobs\\bd2abe19377557ff5771584921f9b65fa041fef0' -> 'C:\\local\\models\\models\\models--stabilityai--sd-turbo\\snapshots\\1681ed09e0cff58eeb41e878a49893228b78b94c\\tokenizer\\tokenizer_config.json'
```

Anyway the benchmark still works, not sure if this files is required or not.

**Comment by rickstaa** [comment] 2024-05-08 11:57
@Titan-Node thanks for the report! I tried to reproduce your problem on my Windows PC but could not reproduce it. I therefore think it is due to a permission problem on your end. Closing this issue for now.

**Closed** 2024-05-08 11:57 UTC
